# Generated by Django 4.0.1 on 2022-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-31 07:15:59.640418+00:00'),
            preserve_default=False,
        ),
    ]
