# Generated by Django 3.2.7 on 2022-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0003_auto_20220202_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
