# Generated by Django 3.2.7 on 2022-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0004_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=7),
            preserve_default=False,
        ),
    ]
