# Generated by Django 3.2.7 on 2022-02-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0005_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='order_item',
        ),
    ]
